### ISSUE TITLE
Relax version of telemetry

### ISSUE THREAD

**Issue by inhji** [keathley/mentat#12]
Could you relax the version requirement for the telemetry module to allow for 1.0 and 0.4?

New versions of telemetry_poller require telemetry version 1.0.0. Telemetry_poller is included in new phoenix projects. Additionally the 1.0 Version does not introduce any breaking changes, so it would be a safe change to make.

Thank you.

**Comment by keathley** [comment]
@inhji No problem. Is this something you'd feel comfortable submitting a PR for?

**Comment by inhji** [comment]
@keathley Definitely! I'll do it in the next few days.

**Comment by vasspilka** [comment]
Hello, @keathley could we also create a minor release for this patch?
