### ISSUE TITLE
Any updates on a new release?

### ISSUE THREAD

**Issue by daveshah** [keathley/mentat#14]
I'm curious to know if there are plans for a release soon. 

I'd love to be able to rely on https://github.com/elixir-toniq/mentat/pull/13 to avoid an override.

Thanks!

**Comment by mhanberg** [comment]
I can see if we can get a release cut!

**Comment by kenpb** [comment]
Hi!,

Any updates?, I see the repo has been already tagged for 0.7.2 but hex doesn't have this version available yet.

Cheers!

**Comment by zorbash** [comment]
Bump. @keathley Would it be possible to publish `0.7.2`?

Thanks!

**Comment by mhanberg** [comment]
I published 0.7.2 to hex. @zorbash @kenpb @daveshah
